print('Dear Mauli,')
print('     I am sorry for zaban larauing with u \n' '     and I truely mean that!')
print('Your sincerly')
print('     Ayra Singh')
print('can u come down to play!?')
print('pleas pleas pleas pleas pleas pleas pleas pleas pleas pleas !')